language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install cmake libunittest++-dev libicu-dev llvm-3.1-dev libboost-program-options-dev
before_script: ./configure
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - piphon@gmail.com
  email:
    on_success: change
    on_failure: always
