# -*- cmake -*-

# - Find Apache Portable Runtime
# Find the APR includes and libraries
# This module defines
#  APR_INCLUDE_DIR and APRUTIL_INCLUDE_DIR, where to find apr.h, etc.
#  APR_LIBRARIES and APRUTIL_LIBRARIES, the libraries needed to use APR.
#  APR_FOUND and APRUTIL_FOUND, If false, do not try to use APR.
# also defined, but not for general use are
#  APR_LIBRARY and APRUTIL_LIBRARY, where to find the APR library.

# APR first.

FIND_PROGRAM(
  APR_CONFIG apr-config
  /usr/bin/include
  /usr/local/bin
)

EXECUTE_PROCESS(COMMAND ${APR_CONFIG} --cppflags OUTPUT_VARIABLE APR_CPPFLAGS   OUTPUT_STRIP_TRAILING_WHITESPACE)
EXECUTE_PROCESS(COMMAND ${APR_CONFIG} --cflags   OUTPUT_VARIABLE APR_CFLAGS     OUTPUT_STRIP_TRAILING_WHITESPACE)
EXECUTE_PROCESS(COMMAND ${APR_CONFIG} --ldflags  OUTPUT_VARIABLE APR_LDFLAGS    OUTPUT_STRIP_TRAILING_WHITESPACE)
EXECUTE_PROCESS(COMMAND ${APR_CONFIG} --includes OUTPUT_VARIABLE APR_INCLUDES   OUTPUT_STRIP_TRAILING_WHITESPACE)

MARK_AS_ADVANCED(
  APR_CPPFLAGS
  APR_CFLAGS
  APR_LDFLAGS
  APR_INCLUDE_DIR
)