/*
 *******************************************************************************
 *   Copyright (C) 2012 Vasiliy Sheredeko
 *   MIT license. All Rights Reserved.
 *******************************************************************************
 */
#ifndef EXAMPLE_SCANNER_H
#define EXAMPLE_SCANNER_H

// Flex expects the signature of yylex to be defined in the macro YY_DECL, and
// the C++ parser expects it to be declared. We can factor both as follows.

#ifndef YY_DECL

#define	YY_DECL						\
    kiwi::lang::Parser::token_type				\
    kiwi::lang::Scanner::lex(				\
	kiwi::lang::Parser::semantic_type* yylval,		\
	kiwi::lang::Parser::location_type* yylloc		\
    )
#endif

#ifndef __FLEX_LEXER_H
#define yyFlexLexer ExampleFlexLexer
#undef yylex
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

#include "parser.hpp"

namespace kiwi {
namespace lang {

/** Scanner is a derived class to add some extra function to the scanner
 * class. Flex itself creates a class named yyFlexLexer, which is renamed using
 * macros to ExampleFlexLexer. However we change the context of the generated
 * yylex() function to be contained within the Scanner class. This is required
 * because the yylex() defined in ExampleFlexLexer has no parameters. */
class Scanner : public ExampleFlexLexer
{
public:
    /** Create a new scanner object. The streams arg_yyin and arg_yyout default
     * to cin and cout, but that assignment is only made when initializing in
     * yylex(). */
    Scanner(std::istream* arg_yyin = 0,
	    std::ostream* arg_yyout = 0);

    /** Required for virtual functions */
    virtual ~Scanner();

    /** This is the main lexing function. It is generated by flex according to
     * the macro declaration YY_DECL above. The generated bison parser then
     * calls this virtual function to fetch new tokens. */
    virtual Parser::token_type lex(
	   Parser::semantic_type* yylval,
	   Parser::location_type* yylloc
	);

    /// Save buffer for lexer
    virtual int LexerInput(char* buf, int max_size);

    virtual void LexerError(const char* msg);

    /// Discard all unknwon function
    virtual void LexerOutput(const char* buf, int size);

    /** Enable debug output (via arg_yyout) if compiled into the scanner. */
    void set_debug(bool b);
};

} // namespace lang
} // namespace kiwi

#endif // EXAMPLE_SCANNER_H
